using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;
using System.Xml.Linq;

namespace A2.Models
{
    public class SportClub
    {
        [DatabaseGenerated(DatabaseGeneratedOption.None)] // makes it none generated by the database. 
        [Display(Name = "Registration Number")]
        [Required]
        public string Id { get; set; }

        [Required]
        [StringLength(50, MinimumLength = 3)]
        public string Title { get; set; }

        [DataType(DataType.Currency)]
        [Column(TypeName ="money")] //Set the column name in the database to money 
        public decimal Fee { get; set; }

        public ICollection<Subscription> Subscriptions { get; set; }
       public ICollection<News> News { get; set; }
    }
}
